import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import SitePage from "@/components/SitePage";
import CarGallery from "@/components/CarGallery";
import { cars, formatPrice } from "@/data/cars";
import { getCarGallery } from "@/data/carGallery";

export function generateStaticParams() { return cars.map(car => ({ id: car.id })); }
export default async function CarPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const car = cars.find(c => c.id === id); if (!car) notFound(); const specs = [["Цена", formatPrice(car.price)],["Двигатель", car.engine],["Объём двигателя", car.engineVolume],["Мощность", car.power],["Трансмиссия", car.transmission],["Пробег", car.mileage ? `${car.mileage.toLocaleString("ru-RU")} км` : "Новый автомобиль"],["Год выпуска", `${car.year} год`],["Привод", car.drive],["Руль", car.wheel],["Тип кузова", car.bodyType],["Цвет", car.color],["Повреждения кузова", car.damage]]; return <SitePage><section className="bg-gray-bg pb-12 pt-28"><div className="shell"><Link href="/catalog" className="inline-flex items-center gap-2 text-sm text-gray-text hover:text-primary"><ArrowLeft size={16}/>Назад в каталог</Link><div className="mt-7 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm text-gray-text">{car.year} · {car.bodyType}</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight text-dark sm:text-4xl">{car.brand} {car.model}</h1></div><p className="text-3xl font-extrabold text-primary">{formatPrice(car.price)}</p></div></div></section><section className="section-space pt-10"><div className="shell grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><aside className="rounded-[20px] border border-gray-border bg-white p-7"><h2 className="mb-4 text-xl font-bold text-dark">Характеристики</h2>{specs.map(([label,value]) => <div key={label} className="flex justify-between gap-4 border-b border-gray-border py-3 text-sm last:border-0"><span className="text-gray-text">{label}</span><strong className="text-right font-semibold text-dark">{value}</strong></div>)}</aside><CarGallery images={getCarGallery(car.id)} alt={`${car.brand} ${car.model}`}/><div className="lg:col-span-2"><h2 className="text-2xl font-bold text-dark">Описание</h2><p className="mt-4 leading-7 text-gray-text">{car.description ?? `${car.brand} ${car.model} ${car.year} года выпуска. Пробег подтверждён, автомобиль обслуживался по регламенту. Кузов без серьёзных повреждений. Автомобиль проверен нашими специалистами и готов к оформлению.`}</p></div></div></section></SitePage>; }
